CFLAGS=-Wall -g

all:
	make ./ex1
	make ./ex3
	make ./ex5
	make ./ex6
	make ./ex7
	make ./ex8
	make ./ex9
	make ./ex10

clean:
	rm -r ex1
	rm -r ex3
	rm -r ex5
	rm -r ex6
	rm -r ex7
	rm -r ex8
	rm -r ex9
	rm -r ex10
